[package]
name = "rusty-os"
version = "0.1.0"
authors = ["sundeep <routhusundeep@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
